# Generated by Django 5.0.7 on 2026-09-14 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('avatar_url', models.URLField(blank=True)),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('auth_provider', models.CharField(choices=[('password', 'Password'), ('google', 'Google'), ('guest', 'Nickname (guest)')], default='password', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
